# Generated by Django 5.0 on 2023-12-30 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, verbose_name='Тип произведения')),
                ('title', models.CharField(verbose_name='Название')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating_imdb', models.IntegerField(verbose_name='Рейтинг IMDB')),
                ('content_rating', models.CharField(verbose_name='Возрастной рейтинг')),
                ('release_date', models.DateField(db_index=True, verbose_name='Дата релиза')),
                ('timing', models.CharField(verbose_name='Хронометраж')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
            ],
        ),
        migrations.CreateModel(
            name='GenreToArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_genre', to='movies.artwork')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_art', to='movies.genre')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.ManyToManyField(db_index=True, through='movies.GenreToArtWork', to='movies.genre', verbose_name='Жанры Фильма'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('art_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_user', to='movies.artwork')),
            ],
        ),
    ]
