# Generated by Django 5.0 on 2024-01-10 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='budget',
            field=models.IntegerField(default=22, verbose_name='Бюджет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='revenue',
            field=models.IntegerField(default=22, verbose_name='Сборы'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen', to='movies.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polzoc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
