# Generated by Django 5.0 on 2024-01-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_artwork_budget_artwork_revenue_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='type',
        ),
    ]
