# Generated by Django 5.0 on 2024-01-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_artwork_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtWork',
            new_name='Movie',
        ),
    ]
