# Generated by Django 5.0 on 2024-01-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_artwork_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretoartwork',
            old_name='art_work',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='art_work',
            new_name='movie',
        ),
    ]
