# Generated by Django 5.0 on 2024-01-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_art_work_genretoartwork_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
