# Generated by Django 5.0 on 2024-01-18 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_budget_alter_movie_content_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content_rating',
            field=models.CharField(verbose_name='Возрастной рейтинг'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_imdb',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDB'),
        ),
    ]
