# Generated by Django 5.0 on 2024-01-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_content_rating_alter_movie_rating_imdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='genretoartwork',
            options={'verbose_name': 'Жанр у фильмов', 'verbose_name_plural': 'Жанры у фильмов'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name': 'Предпочтение', 'verbose_name_plural': 'предпочтения'},
        ),
    ]
